/**
 * Profile fixtures for testing the matching algorithm.
 * Covers: location matrix, technical preferences, priority area overlap,
 * complementarity, and edge cases.
 */

export const currentUserLondonTechnical: OnboardingData = {
  user_id: "current_user_001",
  firstName: "Alex",
  lastName: "Khan",
  title: "Software Engineer",
  city: "London",
  country: "United Kingdom",
  satisfaction: "Happy",
  batteryLevel: "Energized",
  isTechnical: "yes",
  personalIntro: "Full-stack engineer building in AI.",
  ummah: "Building tools for Muslim founders.",
  education: "BSc CS, MIT",
  experience: "2 years at Google",
  lookingFor: "non-technical",
  preferredLocation: "same-country",
  hasStartup: "yes",
  startupName: "FoundrAI",
  startupDescription: "AI co-founder matching.",
  responsibilities: ["Engineering", "Product"],
  priorityAreas: ["AI", "Healthcare", "Fintech"],
  linkedin: "",
  twitter: "",
  git: "",
  personalWebsite: "",
  isHiring: false,
};

/** Same city, technical, high priority overlap - should rank high for same-city users */
export const candidateSameCityTechnical: OnboardingData = {
  user_id: "sim_user_002",
  firstName: "Sarah",
  lastName: "Ahmed",
  title: "Product Manager",
  city: "London",
  country: "United Kingdom",
  satisfaction: "Content",
  batteryLevel: "Energized",
  isTechnical: "no",
  personalIntro: "PM with 5 years in fintech.",
  ummah: "Impact-driven products.",
  education: "MBA, LBS",
  experience: "Product at Revolut",
  lookingFor: "technical",
  preferredLocation: "same-city",
  hasStartup: "yes",
  startupName: "PayStack",
  responsibilities: ["Product", "Sales"],
  priorityAreas: ["AI", "Healthcare", "Fintech"],
  linkedin: "",
  twitter: "",
  git: "",
  personalWebsite: "",
  isHiring: false,
};

/** Same country, different city - should pass same-country filter, rank lower than same-city */
export const candidateSameCountryDifferentCity: OnboardingData = {
  user_id: "sim_user_003",
  firstName: "Omar",
  lastName: "Hassan",
  title: "Business Development",
  city: "Manchester",
  country: "United Kingdom",
  satisfaction: "Browsing",
  batteryLevel: "Content",
  isTechnical: "no",
  personalIntro: "BD lead scaling startups.",
  ummah: "Connecting founders globally.",
  education: "BA Economics, Oxford",
  experience: "BD at Seedcamp",
  lookingFor: "technical",
  preferredLocation: "remote",
  hasStartup: "no",
  priorityAreas: ["AI", "Fintech"],
  linkedin: "",
  twitter: "",
  git: "",
  personalWebsite: "",
  isHiring: false,
};

/** Different country - should be filtered out for same-country preference (when we test filter) */
export const candidateDifferentCountry: OnboardingData = {
  user_id: "sim_user_004",
  firstName: "Leyla",
  lastName: "Yilmaz",
  title: "UX Designer",
  city: "Istanbul",
  country: "Turkey",
  satisfaction: "Happy",
  batteryLevel: "Energized",
  isTechnical: "no",
  personalIntro: "Designing for Muslim markets.",
  ummah: "Design for dignity.",
  education: "MDes, Parsons",
  experience: "Design at Getir",
  lookingFor: "technical",
  preferredLocation: "remote",
  hasStartup: "yes",
  responsibilities: ["Design"],
  priorityAreas: ["Consumer", "Education"],
  linkedin: "",
  twitter: "",
  git: "",
  personalWebsite: "",
  isHiring: false,
};

/** Technical candidate - should be filtered out when lookingFor is "non-technical" */
export const candidateTechnicalFilteredOut: OnboardingData = {
  user_id: "sim_user_005",
  firstName: "Yusuf",
  lastName: "Ali",
  title: "ML Engineer",
  city: "London",
  country: "United Kingdom",
  satisfaction: "Happy",
  batteryLevel: "Content",
  isTechnical: "yes",
  personalIntro: "ML engineer, 3 YOE.",
  ummah: "AI for good.",
  education: "MSc ML, Imperial",
  experience: "DeepMind",
  lookingFor: "non-technical",
  preferredLocation: "same-city",
  hasStartup: "yes",
  responsibilities: ["Engineering"],
  priorityAreas: ["AI", "Healthcare"],
  linkedin: "",
  twitter: "",
  git: "",
  personalWebsite: "",
  isHiring: false,
};

/** High priority overlap with currentUserLondonTechnical */
export const candidateHighOverlap: OnboardingData = {
  user_id: "sim_user_006",
  firstName: "Fatima",
  lastName: "Khan",
  title: "Operations Lead",
  city: "London",
  country: "United Kingdom",
  satisfaction: "Content",
  batteryLevel: "Energized",
  isTechnical: "no",
  personalIntro: "Ops scaling early-stage startups.",
  ummah: "Systems for impact.",
  education: "BSc Business",
  experience: "Ops at Y Combinator portfolio",
  lookingFor: "technical",
  preferredLocation: "same-city",
  hasStartup: "yes",
  responsibilities: ["Ops", "Product"],
  priorityAreas: ["AI", "Healthcare", "Fintech"],
  linkedin: "",
  twitter: "",
  git: "",
  personalWebsite: "",
  isHiring: false,
};

/** No priority overlap - tests diversity scoring */
export const candidateNoOverlap: OnboardingData = {
  user_id: "sim_user_007",
  firstName: "Hassan",
  lastName: "Rashid",
  title: "Educator",
  city: "London",
  country: "United Kingdom",
  satisfaction: "Browsing",
  batteryLevel: "Content",
  isTechnical: "no",
  personalIntro: "Building edtech for underserved communities.",
  ummah: "Education access.",
  education: "PhD Education",
  experience: "Teacher, then founder",
  lookingFor: "technical",
  preferredLocation: "same-country",
  hasStartup: "yes",
  responsibilities: ["Product", "Sales"],
  priorityAreas: ["Education", "Consumer"],
  linkedin: "",
  twitter: "",
  git: "",
  personalWebsite: "",
  isHiring: false,
};

/** Edge case: minimal optional fields */
export const candidateEdgeCaseMinimal: OnboardingData = {
  user_id: "sim_user_008",
  firstName: "Amina",
  lastName: "Said",
  title: "Consultant",
  city: "London",
  country: "United Kingdom",
  satisfaction: "Content",
  batteryLevel: "Content",
  isTechnical: "no",
  personalIntro: "Strategy consultant.",
  ummah: "Impact consulting.",
  education: "MBA",
  experience: "McKinsey",
  lookingFor: "either",
  preferredLocation: "remote",
  hasStartup: "no",
  priorityAreas: ["Healthcare"],
  linkedin: "",
  twitter: "",
  git: "",
  personalWebsite: "",
  isHiring: false,
};

/** All candidates for currentUserLondonTechnical */
export const allCandidates: OnboardingData[] = [
  candidateSameCityTechnical,
  candidateSameCountryDifferentCity,
  candidateDifferentCountry,
  candidateTechnicalFilteredOut,
  candidateHighOverlap,
  candidateNoOverlap,
  candidateEdgeCaseMinimal,
];
